### ISSUE TITLE
1.7-alpha-1版本，GTCEu的Fluxed electrum有关物品（通流琥珀金）翻译错误

### ISSUE THREAD

**Issue by Ede1weiss3181** [zero6six/nomi-ceu-zh_cn#2]
问题：包含矿典名ElectrumFlux的有关物品都被翻译为了琥珀金
相关物品即粉，小堆粉，小撮粉，锭，板，双层板，杆，粒，齿轮，块

复现：
使用JEI
搜索ElectrumFlux
发现相关物品翻译为琥珀金，而并非通流琥珀金

希望的修改结果：将相关物品翻译从琥珀金更正为通流琥珀金

整合包版本：1.7-alpha-1（不排除其他版本也存在这个问题）
使用的语言：简体中文（中国）

额外信息：
我无法给出具体物品的物品id，因为格雷科技物品是使用meta进行搜索的，通流琥珀金的meta为32019
如果想要获取一个通流琥珀金板，应该使用以下指令
/give <player> gregtech:meta_plate 1 32019
其他的相关物品同理，使用代码名+meta的组合就可以搜索到该物品

相关的物品代码名（默认带上了gregtech:的索引）：
粉：meta_dust；小堆粉：meta_dust_small；小撮粉：meta_dust_tiny；锭：meta_item；
板：meta_plate；双层板：meta_plate_double；杆：meta_stick；粒：meta_nugget；齿轮：meta_gear；
其中，唯一的例外是块，它使用了独特的代码名和meta。该物品信息如图
![image](https://github.com/zero6six/nomi-ceu-zh_cn/assets/104157637/9fce4e13-e2f7-433d-8e0b-894cf1d86109)

**Comment by zero6six** [comment]
https://github.com/zero6six/nomi-ceu-zh_cn/blob/8cfb33c9cfe31ce219584ddf233f51fd47c405a2/assets/contenttweaker/lang/zh_cn.lang#L19C36-L19C36
这里的问题，格雷的很多东西都是直接注册材料名的，然后好像我一开始接手翻译的时候这里就一直是被错译的状态。
我这个周末把这个改成通量琥珀金好了，延续 GT6 的翻译（GTCEu 原生只有琥珀金没有通量琥珀金）

**Comment by Ede1weiss3181** [comment]
好的，麻烦了
